version: "3.9"

services:
  api:
    container_name: api
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kimoveis
      - HOST=db
      - SECRET_KEY=secret_key

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules/bcrypt/

  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=kimoveis
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kimoveis"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
